channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.0
- pip:
  - mlflow==2.17.2
  - lz4==4.3.3
  - numpy==1.26.4
  - pandas==2.2.1
  - psutil==5.9.8
  - scikit-learn==1.5.0
  - scipy==1.13.1
  - xgboost==2.1.3
name: mlflow-env
