name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      api:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl --fail http://localhost:8000/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start API server
      run: |
        nohup uvicorn api:app --host 0.0.0.0 --port 8000 &

    - name: Wait for API to be ready
      run: |
        while ! curl --silent --fail http://localhost:8000/; do
          echo 'Waiting for API...'
          sleep 5
        done

    - name: Run tests
      run: |
        pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST 'https://api.render.com/deploy/srv-<your-service-id>?key=${{ secrets.RENDER_API_KEY }}'
